export const PROFESSIONAL_TITLES = [
    "Plumber",
    "Electrician",
    "Carpenter",
    "Handyman",
    "Cleaner",
    "Painter",
    "Gardener",
    "Mover",
    "Web Developer",
    "Mobile Developer",
    "Graphic Designer",
    "UI/UX Designer",
    "Content Writer",
    "Translator",
    "Tutor",
    "Personal Trainer",
    "Yoga Instructor",
    "Photographer",
    "Videographer",
    "Makeup Artist",
    "Hair Stylist",
    "Chef",
    "Event Planner",
    "Accountant",
    "Lawyer",
    "Consultant",
    "Interior Designer",
    "Architect",
    "Mechanic",
    "Driver"
];
